#!/usr/bin/perl -w
# скрипт возвращающий перевод для слова находящегося в буфере
# словарь используется для ранее переводимых слов
# перевод запрашивается внешним скриптом, сохраняется в словарь
# Autor: Eugene Samoylov aka Helius, gHelius@gmail.com
#use strict;
use utf8;
use open qw(:std :utf8);
#use Cwd;

# получить слово для перевода из буфера обмена
my $word = `xclip -o` || die print "ERROR! xclip not found, you need install it: sudo aptitude install xclip";

# проверить что слово было получено
if (!length($word)) {
	die print "ERROR! выделите слово для перевода";
}

# проверить что это одно слово без лишних знаков
if ($word =~m/[^-a-zA-Z]+/) {
	# встречаются не английские
	if ($word =~m/[^-а-яА-Я]+/) {
		# встречаются не русские
		die print "ERROR! $word содержит лишние символы\n";
	} else {
		# только русские
	}
} else {
	# только английские
} 

$word = lc($word);	# преобразуем все буквы в строчные

print "$word\n";
$trl_text = "a";

# попробовать найти это слово в файле
chdir;
unless ( open InFile, "dict.dct" ) {
	system ("touch dict.dct" );
	die print "ERROR! не могу найти файл словаря dict.dct, будет создан пустой файл в домашней дирректории\n";  
}

while ($line = <InFile>) {
		if($line=~m/^$word\=\=/) {
			$line=~m/.*\=\=(.*?)\$\$/; 
			$temp = $1;
			$temp=~s/, /\n/g;
			$trl_text = "_yes_";
			print "\n";
			chomp($temp);
			print "$temp";
			last;
			
		} else {
			$trl_text = "_no_";
		}
  }
close(InFile);

chdir("/usr/local/bin/translater/");

if ($trl_text =~m/_yes_/) {					# если слово найдено в словаре, возвращаем перевод и выходим
} else {
	$trl_text = `./translate $word`;	# вызвать скрипт переводчика передав ему слово
	
	# проверить на корректность перевода
	if (length ($trl_text)) {					# если перевод имеет место быть - добавляем в словарь 

		print "$trl_text";
		$trl_text=~s/^[\n\t\r]+//;			# удалить перенос в начале строки
		$trl_text=~s/[\n\t\r]+/, /g;		# заменить переносы строки на запятую с пробелом - для записи в файл одной строкой
		
		

chdir;
		open(FILE,">> dict.dct");
		print(FILE "$word==$trl_text\$\$0\n");
		close(FILE);
	} else {
		print "Перевод не найден";
	}
}



