#!/usr/bin/perl -w
# скрипт возвращающий перевод для слова находящегося в буфере
# словарь используется для ранее переводимых слов
# перевод запрашивается внешним скриптом, сохраняется в словарь
# Autor: Eugene Samoylov aka Helius, gHelius@gmail.com

use utf8;
use open qw(:std :utf8);


# получить слово для перевода из буфера обмена
my $word = `xclip -o` || die print "ERROR! xclip not found, you need install it: sudo aptitude install xclip";

# проверить что слово было получено
if (!length($word)) {
	die print "ERROR! выделите слово для перевода";
}

# проверить что это одно слово без лишних знаков
if ($word =~m/([^-a-zA-Z]+)/) {
	 die print "ERROR! $word содержит лишние символы: \"$1\"\n";
}

$word = lc($word);	# преобразуем все буквы в строчные

print "$word\n";
$rus_text = "a";

# попробовать найти это слово в файле
chdir;
unless ( open InFile, "dict.dct" ) {
	system ("touch dict.dct" );
	die print "ERROR! не могу найти файл словаря dict.dct, будет создан пустой файл в домашней дирректории\n";  
}

while ($line = <InFile>) {
		if($line=~m/$word/) {
			$line=~m/.*\=\=(.*?)\$\$/; 
			$temp = $1;
			$temp=~s/, /\n/g;
			$rus_text = "_yes_";
			print "\n";
			print "$temp";
			last;
			
		} else {
			$rus_text = "_no_";
		}
  }
close(InFile);

if ($rus_text =~m/_yes_/) {					# если слово найдено в словаре, возвращаем перевод и выходим
} else {
	$rus_text = `translate $word`;	# вызвать скрипт переводчика передав ему слово

	# проверить на корректность перевода
	if (length ($rus_text)) {			# если перевод имеет место быть - добавляем в словарь 
		print "$rus_text";
	
		$rus_text=~s/^[\n\t\r]+//;
		$rus_text=~s/[\n\t\r]+/, /g;


		open(FILE,">> dict.dct");
		print(FILE "$word==$rus_text\$\$0\n");
		close(FILE);
	} else {
		print "Перевод не найден";
	}
}



